### ISSUE TITLE
As a student or Teacher i would like to track my active time on the web.

### ISSUE THREAD

**Issue by Wasi8DCI** [dci-python-backend-assignments/tdd-class-social#16]

**Comment by Wasi8DCI** [comment]
for that I would use tab to track and analysis my activity that how much time I spent on the form/web from the time of login to log out.

**Comment by Wasi8DCI** [comment]
for that I would use tab to track and analysis my activity that how much time I spent on the form/web from the time of login to log out.

**Comment by Wasi8DCI** [comment]
It will more like on the general web. for example if users login with their user id. they would be able to track their progress that how much time they spent on this web, average online session, how many days they were active and what was the most active day etc

**Comment by mathiasbrito-dci** [comment]
I'm having the feeling that this story is out of scope, maybe you would like to select a different one, and we could work on this one later, let's start by implementing the basics. Move this story back to the Backlog and bring a new one to the sprint.

**Comment by Wasi8DCI** [comment]
Okay I’ll move this to the blacklog

**Comment by mathiasbrito-dci** [comment]
Are you closing the Issue because we are dropping the feature? In case you want to implement it later we need to move it back to the backlog in the project.

**Comment by Wasi8DCI** [comment]
I guess I did it accidentally
