### ISSUE TITLE
Models for users/students/teachers and Institution needs to be defined

### ISSUE THREAD

**Issue by mathiasbrito-dci** [dci-python-backend-assignments/tdd-class-social#21]
In order to implement the stories selected in the first sprint we need to define the models. I would suggest using this thread to do so, could anyone suggest a first draft. This task is urgent since it will block the development of some stories in the current sprint. I can only assign 10 people to and issue but all of you needs to participate. 

@dci-python-backend-assignments/dci-python-class-2022

**Comment by Hans-Lambda** [comment]
I will do it tomorrow :D

**Comment by elinamat** [comment]
What do you mean by that Mathias? the Classes? E.g the 1)Post() 2)User() 3)Course() Objects.

**Comment by mathiasbrito-dci** [comment]
Yes. They represent the data that is coming from the database.

**Comment by mathiasbrito-dci** [comment]
@Hans-Lambda, then create a branch called issue_21_models when you're done push it to remote... so we can review and agree on the model you created.

**Comment by Hans-Lambda** [comment]
okay, we will do so. Expect it tomorrow around 17.00 : )

**Comment by petertheprofessional** [comment]
from pydantic import BaseModel


class User(BaseModel):
    username: str
    password: str
    creation_date: int # Date User was created in system
    active: bool


class Person(User):
    first_name: str
    last_name: str
    id_number: int
    gender: str
    email: str
    phone_number: str
    address: str


class Student(Person):
    current_courses: list
    previous_courses: list


class ProspectiveStudent(Person):
    pass


class Teacher(Person):
    pass


class Mentor(Person):
    pass

class Researcher(Person):
    pass


class Organization(User):
    active_emails: list
    contact_numbers: list


class ResearchInstitution(Organization):
    pass

class EducationalInstitution(Organization):
    pass

**Comment by petertheprofessional** [comment]
I just posted a few possible models to this feed, feel free to start a discussion about what we want to add. (not even sure I'm suggesting the correct information)

**Comment by mathiasbrito-dci** [comment]
A student probably has an institution associated, right? A teacher has classes... a Researcher usually belongs to a lab and also a department...

**Comment by Hans-Lambda** [comment]
pull req for models online

**Comment by elinamat** [comment]
I was thinking just one class User() and then separate them as Student(User), Teacher(User) and Institution(User) ...!

class User(BaseModel):
id: str
username: str
password: str
email: str
registration_date: str 
is_active: bool
name: str
address: str
phone_number: str


What about Course() and Post()?!!

**Comment by mathiasbrito-dci** [comment]
Yes, Elina, you are in the right direction, we need to keep the focus... the stories only handle "Studen", "Teacher" and "Institution"... I would suggest incorporating Elina's suggestions into the User model. Please check the #22, the pull request from Billy and Franz, I think we need to discuss it, and try to avoid distractions focus on the relevant models.

**Comment by mathiasbrito-dci** [comment]
I think it will be necessary to create the Institution model - based on the stories selected for this sprint. I'll update the title of this issue then. Other models can appear, but since these are crucial, I'll keep only them in the issue's title.

**Comment by hilabit** [comment]
from pydantic import BaseModel


class User(BaseModel):
    id: str
    is_registered: boolean
    username: str
    password: str
    creation_date: int # Date User was created in system
    first_name: str
    last_name: str
    gender: str
    email: str
    phone_number: str
    address: str


class Student(User):
    subject: list 
    current_courses: list
    previous_courses: list


class Teacher(User):
    current_classes: list
    

class Mentor(User):
    pass

class Researcher(User):
    pass


class Organization(BaseModel):
    active_emails: list
    contact_numbers: list


class ResearchInstitution(Organization):
    pass

class EducationalInstitution(Organization):
    pass

**Comment by elinamat** [comment]
from datetime import datetime
from pydantic import BaseModel


class User(BaseModel):
    id: str
    username: str
    password: str
    email: str
    registration_date: str
    is_active: bool # is User online?
    prospective: bool
    name: str
    address: str
    phone_number: str
    website: str
    connections: [] # "Friends" connections with others


class Anonymous(BaseModel):
    session_id: str
    prospective: bool


class Student(User):
    current_courses: []
    completed_courses: []


class Teacher(User):
    courses_in_progress: []
    old_courses: []
    future_courses: []


class Institution(User):
    description: str
    associates: []
    head_of_organization: str
    research_institution: bool
    education_institution: bool
    research_projects: []
    active_courses: []
    inactive_courses: []
    offers: []


class Post(BaseModel):
    title: str
    body: []
    creator: User
    creation_date: datetime
    type: TypeOfPost
    comments_on_this_post: []
    likes_for_this_post: []
    shares_for_this_post: []
    type_of_post: str


# `EducationObject` is a class that has an `organization`, a list of `members`, a `title`, and a `description`
# It's a class that defines the attributes of an education object.
class EducationObject(BaseModel):
    organization: Organization
    members: []
    title: str
    description: str


# A course is an education object that has a teacher, material, start date, end date, and assignments.
# It's a class that defines the attributes of a course.
class Courses(EducationObject):
    teacher: Teacher
    material: []
    start_date: datetime
    end_date: datetime
    assignments: []

**Comment by mathiasbrito-dci** [comment]
Closed by #23

**Comment by Lamaosman2012** [comment]
@mathiasbrito-dci For Issue #19  we need a "role" attribute in the class User .This is hindering us from implementation
