### ISSUE TITLE
As a teacher i would like to be able to import files to the Main cloud

### ISSUE THREAD

**Issue by IObilly** [dci-python-backend-assignments/tdd-class-social#3]
As a teacher i want to import useful files , documents and cheatsheets and store it in the main cloud and be able to specify access  to whom i gave to , so they will be able to reach and view  this resources (not be able to change it )

**Comment by mathiasbrito-dci** [comment]
Let's limit this issue to file upload. Access control can be handled in a different issue.

**Comment by IObilly** [comment]
ok i will do it this way

**Comment by IObilly** [comment]
#test for importing files
@pytest.fixture
def http_test_client():
    return TestClient(app)


def test_must_always_return_a_list_of_files_and_200_ok(http_test_client):
    _test_file = Path("kk.png")
    _files = {"files": _test_file.open("rb")}
    response = http_test_client.post('/teacher/upload', files=_files)
    assert response.status_code == 200


def test_must_always_return_a_unprocessable_data_and_422(http_test_client):
    response = http_test_client.post('/teacher/upload')
    assert response.status_code == 422

def test_must_return_data_of_type_dict(http_test_client):
    response = http_test_client.post('/teacher/upload')
    assert type(response.json()) == dict

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

#upload endpoint using Fastapi UploadFile 
@upload_router.post('/teacher/upload', tags=["files"])
async def upload(files: List[UploadFile] = File(...)):
    for file in files:
        with open(file.filename, "wb") as f:
            shutil.copyfileobj(file.file, f)
    return {"files": [file.filename for file in files]}

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

#upload files using another aproach with Requests library

InProgress(............)

**Comment by mathiasbrito-dci** [comment]
You need to rename the tests, your are missing "when", in our your test names... it is important, because then we will know when exactly this behavior will be seen in the system... example `when_invalid_data_is_received_return_422_unprocessable_entity`

**Comment by mathiasbrito-dci** [comment]
I see you are saving the file in the server right? What about AWS S3?

**Comment by IObilly** [comment]
yes am saving the file in the server 
i was trying to use Deta Drive library but i thought u will not like it

**Comment by mathiasbrito-dci** [comment]
Definitely, you can use it... the only thing I would advise you to do is to always inform the team about your choice, so we can discuss if the service is the best one, or if there is not a better alternative. I would suggest using the Amazon Free Tier and setup an Amazon S3 instance...

**Comment by IObilly** [comment]
Sure I will do it . Thank you for the advice 😇😊

**Comment by IObilly** [comment]
And sorry for using list comprehension 😂😅

**Comment by mathiasbrito-dci** [comment]
You have to, just avoid creating crazy ones 😄

**Comment by IObilly** [comment]
everything is good , today goal is creating a pull request , nothing is blocking me

**Comment by mathiasbrito-dci** [comment]
Do you have the tests?

**Comment by IObilly** [comment]
yes

**Comment by IObilly** [comment]
def test_must_always_return_a_list_of_files_and_200_ok(http_test_client):
    _test_file = Path("kk.png")
    _files = {"files": _test_file.open("rb")}
    response = http_test_client.post('/teacher/upload', files=_files)
    assert response.status_code == 200


def test_when_invalid_data_is_received_return_unprocessable_data_and_422(http_test_client):
    _files = {}
    response = http_test_client.post('/teacher/upload', files=_files)
    assert response.status_code == 422


def test_must_return_data_of_type_dict(http_test_client):
    response = http_test_client.post('/teacher/upload')
    assert type(response.json()) == dict

**Comment by IObilly** [comment]
```python
upload_router = APIRouter()
deta = Deta("a0h8k6xv_65HMa1HRCRUMWZbJoSmvXDKoxtwxAEoo")
files__ = deta.Drive("myfiles")


@upload_router.post('/teacher/upload', tags=["files"])
async def upload(files: List[UploadFile] = File(...)):
    for file in files:
        files__.put(file.filename, file.file)
        # file_content = await file.read()
        # with open(file.filename, "wb") as f:
        #     f.write(file_content)
        #     shutil.copyfileobj(file.file, f)

    return {"files": [file.filename for file in files]}

```

**Comment by IObilly** [comment]
ican basicly code : files__ = Drive("myfiles")
