### ISSUE TITLE
Issues on Base Schemas  

### ISSUE THREAD

**Issue by hilabit** [dci-python-backend-assignments/tdd-class-social#64]
#issue_1_25_46_55_62

   **how can we filter through different statuses of courses- current, completed, active, old? 
   Do we use `related name` within the DB or do we filter through them in the views files? 
   The problem with `related name` is that when using the same related name for two different fields, they conflict.** 
   
```
   
   class Institution(BaseUser):
    name = models.CharField(max_length=300)
    phone_numbers = models.IntegerField()
    associates = models.ManyToManyField(BaseUser, symmetrical=False, related_name='institutions', blank=True)
    association_requests = models.ManyToManyField(BaseUser, symmetrical=False, related_name='institutions1', blank=True)
    head_of_organization = models.CharField(max_length=300)
    research_institution = models.BooleanField(default=False, null=True, blank=True)
    education_institution = models.BooleanField(default=False, null=True, blank=True)
    research_projects = models.ManyToManyField(ResearchProject, symmetrical=False, related_name='institutions', blank=True)
    active_courses = models.ManyToManyField(Course, symmetrical=False, related_name='institutions1', blank=True)
    inactive_courses = models.ManyToManyField(Course, symmetrical=False, related_name='institutions2', blank=True)
    offers = models.ManyToManyField(Course, symmetrical=False, related_name='institutions3', blank=True)
   
```

**Comment by hilabit** [comment]
not sure why, this issue isn't find when I tag it, so the link to the branch isn't available in the ticket

**Comment by mathiasbrito-dci** [comment]
When we create a ManyToMany relationship, from both sides of the relationship, I can get all data about the related entities. E.g. from Institution, I can get all detailed info about all the courses, including the value for an eventual status field. For that reason it is not necessary to have a different relationship called `active_users` or `inactive_users`. So the only relationship you want is `institution -> course`.

**Comment by hilabit** [comment]
thank you. 
The issue was resolved in class. 
I'm closing it as Victor asked me.
